FROM php:7.2-alpine
RUN apk add composer icu-dev libpng-dev
RUN docker-php-ext-install pdo_mysql && docker-php-ext-install intl && docker-php-ext-install gd
RUN docker-php-ext-install zip
WORKDIR "/app"
