base: 'https://www.cg-grafing.de/'
baseVariants:
  -
    base: 'https://cg-grafing.ddev.site'
    condition: 'getenv("IS_DDEV_PROJECT") == "true"'
  -
    base: 'https://cg-grafing.felliweb.de'
    condition: 'applicationContext == "Development"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: de
rootPageId: 1
routeEnhancers:
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    limitToPages:
      - 5
      - 17
    routes:
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
websiteTitle: ''
